-- Database schema (Supabase / Postgres)
-- Run this in the Supabase SQL Editor on a fresh project to set up the tables
-- the bot expects. See database/manager.py for how each table is queried.

CREATE TABLE playlist (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_name VARCHAR NOT NULL,
    owner_id      BIGINT NOT NULL  -- Discord user snowflake; must be BIGINT, not INT (overflows int4)
);

CREATE TABLE songs (
    song_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT NOT NULL REFERENCES playlist(id),  -- no ON DELETE CASCADE:
                                                           -- /deleteplaylist requires the playlist to be
                                                           -- emptied via /clearplaylist first
    song_link   VARCHAR NOT NULL,
    song_title  TEXT NOT NULL
);

CREATE TABLE song_leaderboard (
    video_id   VARCHAR(15) PRIMARY KEY,  -- YouTube video IDs are 11 chars; 15 leaves headroom
    title      TEXT NOT NULL,
    play_count INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
